pipeline {

  agent any

  parameters {
    gitParameter(name: 'GIT_BRANCH_TAG', type: 'PT_BRANCH_TAG',
      branch: '', branchFilter: 'origin/(.*)', defaultValue: 'master',
      description: '', quickFilterEnabled: false, selectedValue: 'NONE', sortMode: 'ASCENDING', listSize: '0')
  }

  options {
    buildDiscarder(
      logRotator(daysToKeepStr: '-1', numToKeepStr: '5', artifactDaysToKeepStr: '-1', artifactNumToKeepStr: '-1')
    )
  }

  stages {

    stage('Gradle build') {
      steps {
        checkout scm: scmGit(
            branches: [[name: "origin/${params.GIT_BRANCH_TAG}"]]
        )
        withGradle {
          sh './gradlew build'
        }
      }
    }

  }

}