pipeline {

  // Defendev_main_checkout

  agent {
    label 'built-in'
  }

  parameters {
    gitParameter(name: 'GIT_BRANCH_TAG', type: 'PT_BRANCH_TAG',
      branch: '', branchFilter: 'origin/(.*)', defaultValue: 'master',
      description: '', quickFilterEnabled: false, selectedValue: 'NONE', sortMode: 'ASCENDING', listSize: '0')
  }

  options {
    buildDiscarder(
      logRotator(daysToKeepStr: '-1', numToKeepStr: '5', artifactDaysToKeepStr: '-1', artifactNumToKeepStr: '-1')
    )
  }

  stages {
    stage('Checkout PBook Git repo') {
      steps {
        checkout scm: scmGit(
          branches: [[name: "origin/${params.GIT_BRANCH_TAG}"]],
          doGenerateSubmoduleConfigurations: false,
          extensions: [],
          gitTool: 'Default',
          submoduleCfg: [],
          userRemoteConfigs: [[
            credentialsId: 'cred.jenkins-ssh-key',
            url: 'git@github.com:jtokarski/defendev.git'
          ]]
        ), poll: false
      }
    }
  }

}